-- Fix the Constructible Area --
-- if technologyUnlocked("ConstructibleArea1") then
-- 	createConstructibleArea1()
-- end
-- if technologyUnlocked("DeepStorage") then
-- 	createDeepStorageArea()
-- end