if global.MF ~= nil then
	global.MF.__index = nil
	global.MF.new = nil
	global.MF.contruct = nil
	global.MF.remove = nil
	global.MF.rebuild = nil
	global.MF.syncFChest = nil
	global.MF.getLaserRadius = nil
	global.MF.getLaserEnergyDrain = nil
	global.MF.getLaserFluidDrain = nil
	global.MF.getLaserItemDrain = nil
	global.MF.getLaserNumber = nil
	global.MF.shield = nil
	global.MF.maxShield = nil
	global.MF.update = nil
	global.MF.updateLasers = nil
	global.MF.updateFuel = nil
	global.MF.updateShield = nil
	global.MF.SendQuatron = nil
end