----------------------------- Quatron ------------------------
require("prototypes/item/quatron-functions.lua")

createQuatron(1, {{"fluid", "DimensionalFluid", 100}, {"fluid", "mfHydrogen",250}})
createQuatron(2, {{"fluid", "LiquidQuatron1", 100}, {"item", "stone",5}})
createQuatron(3, {{"fluid", "LiquidQuatron2",100}, {"item", "stone",10}})
createQuatron(4, {{"fluid", "LiquidQuatron3",100}, {"item", "stone",15}})
createQuatron(5, {{"fluid", "LiquidQuatron4",100}, {"fluid", "water",200}})
createQuatron(6, {{"fluid", "LiquidQuatron5",100}, {"fluid", "water",300}})
createQuatron(7, {{"fluid", "LiquidQuatron6",100}, {"fluid", "water",400}})
createQuatron(8, {{"fluid", "LiquidQuatron7",100}, {"fluid", "mfOxygen",200}})
createQuatron(9, {{"fluid", "LiquidQuatron8",100}, {"fluid", "mfOxygen",300}})
createQuatron(10, {{"fluid", "LiquidQuatron9",100}, {"fluid", "mfOxygen",400}})
createQuatron(11, {{"fluid", "LiquidQuatron10",100}, {"item", "DimensionalCrystal",1}})
createQuatron(12, {{"fluid", "LiquidQuatron11",100}, {"fluid", "mfChlorine", 50}})
createQuatron(13, {{"fluid", "LiquidQuatron12",100}, {"fluid", "mfChlorine", 100}})
createQuatron(14, {{"fluid", "LiquidQuatron13",100}, {"fluid", "mfChlorine", 150}})
createQuatron(15, {{"fluid", "LiquidQuatron14",100}, {"item", "mfSodiumHydroxide", 50}})
createQuatron(16, {{"fluid", "LiquidQuatron15",100}, {"item", "mfSodiumHydroxide", 100}})
createQuatron(17, {{"fluid", "LiquidQuatron16",100}, {"item", "mfSodiumHydroxide", 150}})
createQuatron(18, {{"fluid", "LiquidQuatron17",100}, {"fluid", "mfUranium", 50}})
createQuatron(19, {{"fluid", "LiquidQuatron18",100}, {"fluid", "mfUranium", 100}})
createQuatron(20, {{"fluid", "LiquidQuatron19",100}, {"fluid", "mfUranium", 150}})

createQuatronTechnology()