----------------------------- Quatron ------------------------
require("prototypes/item/quatron-functions.lua")

createQuatron(1, {{"fluid", "DimensionalFluid", 1000}, {"fluid", "mfOxygen",50}})
createQuatron(2, {{"fluid", "LiquidQuatron1", 1000}, {"fluid", "mfHydrogen",5}, {"item", "stone",10}})
createQuatron(3, {{"fluid", "LiquidQuatron2",1000}, {"fluid", "mfHydrogen",5}, {"item", "mfSand",20}})
createQuatron(4, {{"fluid", "LiquidQuatron3",1000}, {"fluid", "mfHydrogen",5}, {"item", "coal",20}})
createQuatron(5, {{"fluid", "LiquidQuatron4",1000}, {"fluid", "mfHydrogen",5}, {"item", "mfGraphite",20}})
createQuatron(6, {{"fluid", "LiquidQuatron5",1000}, {"item", "mfSalt",12}})
createQuatron(7, {{"fluid", "LiquidQuatron6",1000}, {"item", "mfSodium",11}})
createQuatron(8, {{"fluid", "LiquidQuatron7",1000}, {"item", "sulfur",10}})
createQuatron(9, {{"fluid", "LiquidQuatron8",1000}, {"item", "mfSodiumHydroxide",30}})
createQuatron(10, {{"fluid", "LiquidQuatron9",1000}, {"fluid", "mfChlorine",20}})
createQuatron(11, {{"fluid", "LiquidQuatron10",1000}, {"item", "DimensionalCrystal",1}})
createQuatron(12, {{"fluid", "LiquidQuatron11",1000}, {"item", "mfClorodin", 10}, {"item", "coal",20}})
createQuatron(13, {{"fluid", "LiquidQuatron12",1000}, {"item", "mfClorodin", 10}, {"item", "mfGraphite",20}})
createQuatron(14, {{"fluid", "LiquidQuatron13",1000}, {"item", "mfClorodin", 10}, {"item", "mfNanoporeSilicon",5}})
createQuatron(15, {{"fluid", "LiquidQuatron14",1000}, {"item", "mfHydroxyclorodin", 20}, {"item", "mfNanoporeSilicon",5}})
createQuatron(16, {{"fluid", "LiquidQuatron15",1000}, {"fluid", "mfUranium", 50}, {"item", "mfNanoporeSilicon",3}})
createQuatron(17, {{"fluid", "LiquidQuatron16",1000}, {"fluid", "mfFluorodin", 50}, {"item", "mfNanoporeSilicon",3}})
createQuatron(18, {{"fluid", "LiquidQuatron17",1000}, {"fluid", "mfFluorodinII", 50}, {"item", "mfNanoporeSilicon",3}})
createQuatron(19, {{"fluid", "LiquidQuatron18",1000}, {"fluid", "mfFluorodinIII", 50}, {"item", "mfNanoporeSilicon",3}})
createQuatron(20, {{"fluid", "LiquidQuatron19",1000}, {"item", "mfHydroxyclorodin", 20}, {"item", "mfNanoporeSilicon",3}})

createQuatronTechnology()